return [[

┌─┐┌┬┐┌┐ ┬─┐┌─┐┌─┐┌─┐  ┌─┐┬─┐┌─┐┌─┐┌┬┐┬┬  ┬┬┌┬┐┬ ┬   ┌┐┌┌─┐┌┬┐  ┌─┐┬ ┬┌─┐┌─┐┌─┐
├┤ │││├┴┐├┬┘├─┤│  ├┤   │  ├┬┘├┤ ├─┤ │ │└┐┌┘│ │ └┬┘   ││││ │ │   │  ├─┤├─┤│ │└─┐
└─┘┴ ┴└─┘┴└─┴ ┴└─┘└─┘  └─┘┴└─└─┘┴ ┴ ┴ ┴ └┘ ┴ ┴  ┴ ┘  ┘└┘└─┘ ┴   └─┘┴ ┴┴ ┴└─┘└─┘o

Trusted by millions of developers, Kohl's Admin is your all-in-one solution for effortless experience management.
Streamline moderation, elevate gameplay, and nurture a thriving community — all with a powerful, versatile, and user-friendly tool.

Use Kohl's Admin to:
	- 🛠️ Easily moderate your game!
	- 💵 Earn Robux by selling gamepasses and more!
	- ✨ Enhance your experience with fun and useful commands!

💡 Have a suggestion or a problem? Check out our community resources:
https://devforum.roblox.com/t/-/3163723

🚀 We've poured thousands of hours into Kohl's Admin. If you find it helpful, we'd love for you to leave a review – your feedback is invaluable:
https://create.roblox.com/store/asset/172732271/Kohls-Admin

⭐ Getting Started:
	- Move Kohl's Admin in 'ServerScriptService`
	- Add custom commands under Config -> Addons
	- Configure roles, gamepasses, and more in Config -> Settings
	- To sell gamepasses with Kohl's Admin 'ThirdPartySales' must be enabled:
		- Go to File -> Game Settings -> Security -> Tick 'Allow Third Party Sales' and Save

]]
