return {
	{
		Title = "Creator",
		Users = {
			{
				Id = 44391621,
				Tooltip = "Thanks for using Kohl's Admin, if you have any issues feel free to contact me!",
			},
		},
	},
	{
		Title = "Contributors",
		Users = {
			{
				Id = 521855368, -- rfov
				Tooltip = "Design, planning, and expert advice",
			},
			{
				Id = 15554260, -- zeejaym
				Tooltip = "Design, planning, website, and expert advice",
			},
			{
				Id = 1022854840, -- jjj
				Tooltip = "Modeling, UGC, and design advice",
			},
			{
				Id = 15303771, -- Fragility
				Tooltip = "Design, planning, and quality assurance",
			},
		},
	},
	{
		Title = "Support Team",
		Users = {
			4847574, -- mets
			195261420, -- exobyte
			34047620, -- wackiepirate
			208790398, -- chan
			2861326436, -- delzi
			3357116228, -- lemon
			1299780523, -- erazias
			1686847974, -- stone
			93371639, -- 9_ine
			800630, -- jason
		},
	},
	{
		Title = "Testers",
		Users = {
			75214485, -- ericance
			35818691, -- greeny
			1560379748, -- mosha
			2258246, -- emp
			129134882, -- horracecat
			146573772, -- metallochrome
			496062049, -- packiswack
			1279022258, -- arcane
			77608258, -- icarus
			2297254, -- min
			672360774, -- xaz
			9345226, -- tomspell
		},
	},
	{
		Title = "Inspiration",
		Users = {
			{
				Id = 1237666, -- Sceleratis
				Tooltip = "For being spooky skeleton and having the best forks",
			},
			{
				Id = 648020, -- trick555
				Tooltip = "For the introduction to clan development",
			},
			{
				Id = 214258, -- Person299
				Tooltip = "For inspiring the original Kohl's Admin Commands",
			},
			{
				Id = 1670764, -- Elttob
				Tooltip = "Fusion",
			},
			{
				Id = 92658764, -- evaera
				Tooltip = "Cmdr & Moonwave",
			},
		},
	},
	{
		Title = "Special Thanks",
		Users = {
			{
				Id = 46236725, -- Doroku
				Tooltip = "CHAIR!",
			},
			{
				Id = 3286467, -- lejam7890
				Tooltip = "For all the memes",
			},
			{
				Id = 18486567, -- Kensai666
				Tooltip = "Kohl's Realm 3 when?",
			},
			{
				Id = 329424041, -- chamullow
				Tooltip = "GoT RP and Bingo King",
			},
		},
	},
}
