return {
	{
		Title = "Core Contributors",
		Users = {
			{
				Id = 44391621, -- kohl
				Tooltip = "Thanks for using Kohl's Admin, if you have any issues please visit the Kohl's Admin Community Resource on the Roblox DevForums!",
			},
			{
				Id = 521855368, -- rfov
				Tooltip = "Design, planning, and expert advice",
			},
			{
				Id = 15554260, -- zeejaym
				Tooltip = "Design, planning, website, and expert advice",
			},
		},
	},
	{
		Title = "Major Contributors",
		Users = {
			{
				Id = 1022854840, -- jjj
				Tooltip = "Modeling, UGC, and design advice",
			},
			{
				Id = 15303771, -- Fragility
				Tooltip = "Design, planning, and quality assurance",
			},
		},
	},
	{
		Title = "Support Team",
		Users = {
			4847574, -- mets
			195261420, -- exobyte
			34047620, -- wackiepirate
			208790398, -- chan
			2861326436, -- delzi
			3357116228, -- lemon
			1299780523, -- erazias
			1686847974, -- stone
			93371639, -- 9_ine
			800630, -- jason
			3470429081, -- Mercury
			1142396048, -- Franklin_Surten (H)
                        483215789, -- seil
		},
	},
	{
		Title = "Contributors",
		Users = {
			{
				Id = 41336494, -- Calculatous
				Tooltip = "Design, planning, and quality assurance",
			},
			{
				Id = 35818691, -- greeny
				Tooltip = "Documentation and quality assurance",
			},
			{
				Id = 83478451, -- stevendahfish
				Tooltip = "Documentation and quality assurance",
			},
			{
				Id = 345072461, -- raenlua
				Tooltip = "Development Containers",
			},
		},
	},
	{
		Title = "Testers",
		Users = {
			130170862, -- matsagor1
			75214485, -- ericance
			1560379748, -- mosha
			200565345, -- easternbloxxer
			107192912, -- britishtrainspotting
			2258246, -- emp
			129134882, -- horracecat
			146573772, -- metallochrome
			496062049, -- pachiswack
			1279022258, -- arcane
			77608258, -- icarus
			2297254, -- min
			672360774, -- xaz
			9345226, -- tomspell
			3230955923, -- napiw
			516417505, -- landon
			105503420, -- general_legendary
			190022817, -- emblazes
			1224156917, -- dalien
		},
	},
	{
		Title = "Inspiration",
		Users = {
			{
				Id = 1237666, -- Sceleratis
				Tooltip = "The best forks with inspiration from Adonis & EISS",
			},
			{
				Id = 214258, -- Person299
				Tooltip = "For inspiring the original Kohl's Admin Commands with Person299's Admin Commands V2",
			},
			{
				Id = 92658764, -- evaera
				Tooltip = " Moonwave, Promises, & inspiration from Cmdr",
			},
			{
				Id = 2722909519, -- sona
				Tooltip = "Squash & inspiration from data-oriented magic",
			},
			{
				Id = 80119, -- stravant
				Tooltip = "Signal Class",
			},
			{
				Id = 82347291, -- ForeverHD
				Tooltip = "TopbarPlus & inspiration from HD Admin",
			},
			{
				Id = 2032622, -- CloneTrooper1019
				Tooltip = "Classic Build Tools",
			},
			{
				Id = 4812582, -- Sharksie
				Tooltip = "Classic Sword",
			},
			{
				Id = 648020, -- trick555
				Tooltip = "For the introduction to Roblox group development",
			},
			{
				Id = 1670764, -- Elttob
				Tooltip = "Inspiring Flux with Fusion",
			},
		},
	},
	{
		Title = "Special Thanks",
		Users = {
			{
				Id = 70540486, -- reru
				Tooltip = "Lord of the bytes",
			},
			{
				Id = 46236725, -- Doroku
				Tooltip = "CHAIR!",
			},
			{
				Id = 3286467, -- lejam7890
				Tooltip = "For all the memes",
			},
			{
				Id = 18486567, -- Kensai666
				Tooltip = "Kohl's Realm 3 when?",
			},
			{
				Id = 329424041, -- chamullow
				Tooltip = "GoT RP and Bingo King",
			},
		},
	},
}
