local a = Instance.new "Frame"
a.Name = "List"
a.ZIndex = 6
a.Visible = false
a.Size = UDim2.new(0, 200, 0, 20)
a.BorderColor3 = Color3.fromRGB(0, 0, 0)
a.BackgroundTransparency = 1
a.Position = UDim2.new(0.5, -100, 0.5, -100)
a.Active = true
a.BorderSizePixel = 0
a.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
local b = Instance.new "TextButton"
b.Name = "Close"
b.AutoLocalize = false
b.Localize = false
b.ZIndex = 7
b.Size = UDim2.new(0, 20, 0, 20)
b.BorderColor3 = Color3.fromRGB(0, 0, 0)
b.BackgroundTransparency = 1
b.Position = UDim2.new(1, -20, 0, 0)
b.BorderSizePixel = 0
b.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
b.Modal = true
b.FontSize = 6
b.TextStrokeTransparency = 0.75
b.TextSize = 18
b.TextColor3 = Color3.fromRGB(255, 255, 255)
b.Text = "X"
b.Font = 1
b.Parent = a
local c = Instance.new "TextButton"
c.Name = "Hide"
c.AutoLocalize = false
c.Localize = false
c.ZIndex = 7
c.Size = UDim2.new(0, 20, 0, 20)
c.BorderColor3 = Color3.fromRGB(0, 0, 0)
c.BackgroundTransparency = 1
c.Position = UDim2.new(1, -40, 0, 0)
c.BorderSizePixel = 0
c.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
c.Modal = true
c.FontSize = 7
c.TextStrokeTransparency = 0.75
c.TextSize = 24
c.TextColor3 = Color3.fromRGB(255, 255, 255)
c.Text = "-"
c.Font = 1
c.Parent = a
local d = Instance.new "TextLabel"
d.Name = "Title"
d.AutoLocalize = false
d.Localize = false
d.ZIndex = 7
d.Size = UDim2.new(1, -45, 0, 20)
d.BorderColor3 = Color3.fromRGB(0, 0, 0)
d.BackgroundTransparency = 1
d.Position = UDim2.new(0, 5, 0, 0)
d.BorderSizePixel = 0
d.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
d.FontSize = 6
d.TextStrokeTransparency = 0.75
d.TextSize = 18
d.TextColor3 = Color3.fromRGB(255, 255, 255)
d.Text = ""
d.Font = 4
d.TextXAlignment = 0
d.Parent = a
local e = Instance.new "Frame"
e.Name = "BG"
e.ZIndex = 6
e.Size = UDim2.new(1, 0, 0, 200)
e.BorderColor3 = Color3.fromRGB(0, 0, 0)
e.BackgroundTransparency = 0.8
e.Position = UDim2.new(0, 0, 0, 21)
e.BorderSizePixel = 0
e.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
e.Parent = a
local f = Instance.new "Frame"
f.Name = "Bar"
f.ZIndex = 6
f.Size = UDim2.new(1, 0, 1, 0)
f.BorderColor3 = Color3.fromRGB(0, 0, 0)
f.BackgroundTransparency = 0.8
f.BorderSizePixel = 0
f.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
f.Parent = a
local g = Instance.new "ScrollingFrame"
g.Name = "List"
g.ZIndex = 7
g.Size = UDim2.new(1, 0, 0, 200)
g.BorderColor3 = Color3.fromRGB(0, 0, 0)
g.BackgroundTransparency = 1
g.Position = UDim2.new(0, 0, 0, 21)
g.Active = true
g.BorderSizePixel = 0
g.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
g.ScrollingDirection = 2
g.CanvasSize = UDim2.new(1, 0, 1, -20)
g.MidImage = "rbxassetid://305807572"
g.ScrollBarThickness = 5
g.TopImage = "rbxassetid://305807549"
g.BottomImage = "rbxassetid://305807605"
g.Parent = a

return a
