local a = Instance.new "ImageButton"
a.Name = "Direct"
a.ZIndex = 100
a.Visible = false
a.AnchorPoint = Vector2.new(0.5, 0.5)
a.Size = UDim2.new(0, 250, 0, 125)
a.Selectable = false
a.ClipsDescendants = true
a.Position = UDim2.new(0.5, 0, 0.5, 0)
a.Active = false
a.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
a.AutoButtonColor = false
local b = Instance.new "UICorner"
b.Parent = a
local c = Instance.new "TextBox"
c.Name = "Link"
c.LayoutOrder = 1
c.ZIndex = 101
c.AnchorPoint = Vector2.new(0, 1)
c.Size = UDim2.new(1, 0, 0, 32)
c.BackgroundTransparency = 0.9
c.Position = UDim2.new(0, 0, 1, 0)
c.BorderSizePixel = 0
c.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
c.FontSize = 7
c.TextSize = 20
c.TextColor3 = Color3.fromRGB(255, 255, 255)
c.Text = "roblox.com/game-pass/5411126"
c.TextEditable = false
c.Font = 3
c.ClearTextOnFocus = false
c.Parent = a
local d = Instance.new "UICorner"
d.CornerRadius = UDim.new(0, 4)
d.Parent = c
local e = Instance.new "UIPadding"
e.PaddingTop = UDim.new(0, 8)
e.PaddingBottom = UDim.new(0, 8)
e.PaddingLeft = UDim.new(0, 8)
e.PaddingRight = UDim.new(0, 8)
e.Parent = a
local f = Instance.new "TextLabel"
f.Name = "Title"
f.ZIndex = 101
f.Size = UDim2.new(1, -24, 0, 20)
f.BackgroundTransparency = 1
f.Position = UDim2.new(0, 0, 0, -2)
f.BorderSizePixel = 0
f.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
f.FontSize = 7
f.TextSize = 20
f.TextColor3 = Color3.fromRGB(255, 255, 255)
f.Text = "Kohl's Admin Donation"
f.Font = 4
f.TextXAlignment = 0
f.Parent = a
local g = Instance.new "TextLabel"
g.Name = "Content"
g.ZIndex = 101
g.Size = UDim2.new(1, 0, 0, 28)
g.BackgroundTransparency = 1
g.Position = UDim2.new(0, 0, 0, 24)
g.BorderSizePixel = 0
g.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
g.FontSize = 5
g.TextSize = 14
g.TextColor3 = Color3.fromRGB(255, 255, 255)
g.Text = "This game does not allow third party sales.\nCopy the link below to donate directly."
g.TextWrapped = true
g.TextWrap = true
g.Font = 3
g.Parent = a
local h = Instance.new "TextLabel"
h.Name = "Warning"
h.ZIndex = 101
h.Size = UDim2.new(1, 0, 0, 14)
h.BackgroundTransparency = 1
h.Position = UDim2.new(0, 0, 0, 60)
h.BorderSizePixel = 0
h.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
h.FontSize = 5
h.TextSize = 14
h.TextColor3 = Color3.fromRGB(255, 0, 0)
h.Text = "You will need to rejoin the game for perks!"
h.Font = 4
h.Parent = a
local i = Instance.new "ImageButton"
i.Name = "Close"
i.ZIndex = 101
i.AnchorPoint = Vector2.new(1, 0)
i.Size = UDim2.new(0, 24, 0, 24)
i.BackgroundTransparency = 1
i.Position = UDim2.new(1, 4, 0, -4)
i.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
i.Image = "rbxassetid://10178707604"
i.Parent = a

return a
