local a = Instance.new "Frame"
a.Name = "Credit"
a.Size = UDim2.new(1, 0, 1, 0)
a.BorderColor3 = Color3.fromRGB(0, 0, 0)
a.BackgroundTransparency = 1
a.BorderSizePixel = 0
a.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
local b = Instance.new "ImageButton"
b.Name = "Toggle"
b.ZIndex = 10
b.Size = UDim2.new(0, 57, 0, 22)
b.BorderColor3 = Color3.fromRGB(0, 0, 0)
b.BackgroundTransparency = 1
b.Position = UDim2.new(1, -60, 1, -25)
b.BorderSizePixel = 0
b.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
b.AutoButtonColor = false
b.Image = "rbxassetid://306774746"
b.Parent = a
local c = Instance.new "Frame"
c.Name = "Main"
c.ZIndex = 9
c.Visible = false
c.Size = UDim2.new(0, 250, 0, 20)
c.BorderColor3 = Color3.fromRGB(0, 0, 0)
c.BackgroundTransparency = 1
c.Position = UDim2.new(0.5, -125, 0.5, -130)
c.Active = true
c.BorderSizePixel = 0
c.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
c.Parent = a
local d = Instance.new "Frame"
d.Name = "BG"
d.ZIndex = 7
d.Size = UDim2.new(1, 0, 0, 198)
d.BorderColor3 = Color3.fromRGB(0, 0, 0)
d.BackgroundTransparency = 0.7
d.Position = UDim2.new(0, 0, 0, 21)
d.BorderSizePixel = 0
d.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
d.Parent = c
local e = Instance.new "TextLabel"
e.Name = "T1"
e.AutoLocalize = false
e.Localize = false
e.ZIndex = 10
e.Size = UDim2.new(1, -10, 0, 40)
e.BorderColor3 = Color3.fromRGB(0, 0, 0)
e.BackgroundTransparency = 1
e.Position = UDim2.new(0, 5, 0, 5)
e.BorderSizePixel = 0
e.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
e.FontSize = 6
e.TextStrokeTransparency = 0.75
e.TextSize = 18
e.TextColor3 = Color3.fromRGB(255, 255, 255)
e.TextYAlignment = 0
e.Text = "This game uses Kohl's Admin Infinite, created by Scripth!"
e.TextWrapped = true
e.TextWrap = true
e.Font = 3
e.Parent = d
local f = Instance.new "TextLabel"
f.Name = "T2"
f.AutoLocalize = false
f.Localize = false
f.ZIndex = 10
f.Size = UDim2.new(1, -10, 0, 40)
f.BorderColor3 = Color3.fromRGB(0, 0, 0)
f.BackgroundTransparency = 1
f.Position = UDim2.new(0, 5, 0, 75)
f.BorderSizePixel = 0
f.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
f.FontSize = 6
f.TextStrokeTransparency = 0.75
f.TextSize = 18
f.TextColor3 = Color3.fromRGB(255, 255, 255)
f.Text = "Enjoy the Admin?\nRate it & donate for cool stuff!"
f.TextWrapped = true
f.TextWrap = true
f.Font = 3
f.Parent = d
local g = Instance.new "TextLabel"
g.Name = "T3"
g.AutoLocalize = false
g.Localize = false
g.ZIndex = 10
g.Size = UDim2.new(1, -10, 0, 20)
g.BorderColor3 = Color3.fromRGB(0, 0, 0)
g.BackgroundTransparency = 1
g.Position = UDim2.new(0, 5, 0, 145)
g.BorderSizePixel = 0
g.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
g.FontSize = 6
g.TextStrokeTransparency = 0.75
g.TextSize = 18
g.TextColor3 = Color3.fromRGB(255, 255, 255)
g.TextYAlignment = 0
g.Text = "VIP Commands"
g.TextWrapped = true
g.TextWrap = true
g.Font = 4
g.Parent = d
local uIGradient_g = Instance.new("UIGradient")
uIGradient_g.Name = "UIGradient"
uIGradient_g.Color = ColorSequence.new({
	ColorSequenceKeypoint.new(0, Color3.fromRGB(127, 0, 255)),
	ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 0, 127)),
})
uIGradient_g.Rotation = -90
uIGradient_g.Parent = g
local i = Instance.new "TextButton"
i.Name = "Close"
i.AutoLocalize = false
i.Localize = false
i.ZIndex = 10
i.Size = UDim2.new(0, 20, 0, 20)
i.BorderColor3 = Color3.fromRGB(0, 0, 0)
i.BackgroundTransparency = 1
i.Position = UDim2.new(1, -20, 0, 0)
i.BorderSizePixel = 0
i.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
i.FontSize = 6
i.TextStrokeTransparency = 0.75
i.TextSize = 18
i.TextColor3 = Color3.fromRGB(255, 255, 255)
i.Text = "X"
i.Font = 1
i.Parent = c
local j = Instance.new "TextLabel"
j.Name = "Title"
j.AutoLocalize = false
j.Localize = false
j.ZIndex = 10
j.Size = UDim2.new(1, -25, 0, 20)
j.BorderColor3 = Color3.fromRGB(0, 0, 0)
j.BackgroundTransparency = 1
j.Position = UDim2.new(0, 5, 0, 0)
j.BorderSizePixel = 0
j.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
j.FontSize = 6
j.TextStrokeTransparency = 0.75
j.TextSize = 18
j.TextColor3 = Color3.fromRGB(255, 255, 255)
j.Text = "Kohl's Admin Credit"
j.Font = 4
j.TextXAlignment = 0
j.Parent = c
local k = Instance.new "Frame"
k.Name = "Bar"
k.ZIndex = 8
k.Size = UDim2.new(1, 0, 1, 0)
k.BorderColor3 = Color3.fromRGB(0, 0, 0)
k.BackgroundTransparency = 0.7
k.BorderSizePixel = 0
k.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
k.Parent = c
local l = Instance.new "TextButton"
l.Name = "Get"
l.AutoLocalize = false
l.Localize = false
l.ZIndex = 9
l.Size = UDim2.new(0, 90, 0, 20)
l.BorderColor3 = Color3.fromRGB(0, 0, 0)
l.BackgroundTransparency = 0.5
l.Position = UDim2.new(0.5, -45, 0, 70)
l.BorderSizePixel = 0
l.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
l.FontSize = 6
l.TextStrokeTransparency = 0.9
l.TextSize = 18
l.TextColor3 = Color3.fromRGB(0, 0, 0)
l.Text = "Get it Now!"
l.Font = 4
l.Parent = c
local m = Instance.new "TextButton"
m.Name = "D2"
m.AutoLocalize = false
m.Localize = false
m.ZIndex = 9
m.Size = UDim2.new(0, 75, 0, 20)
m.BorderColor3 = Color3.fromRGB(0, 0, 0)
m.BackgroundTransparency = 0.5
m.Position = UDim2.new(0.5, 3, 0, 140)
m.BorderSizePixel = 0
m.BackgroundColor3 = Color3.fromRGB(0, 255, 0)
m.FontSize = 6
m.TextStrokeTransparency = 0.75
m.TextSize = 18
m.TextColor3 = Color3.fromRGB(255, 255, 255)
m.Text = "100 R$"
m.Font = 4
m.Parent = c
local n = Instance.new "TextButton"
n.Name = "Trail"
n.AutoLocalize = false
n.Localize = false
n.ZIndex = 9
n.Visible = false
n.Size = UDim2.new(0, 82, 0, 20)
n.BorderColor3 = Color3.fromRGB(0, 0, 0)
n.BackgroundTransparency = 0.5
n.Position = UDim2.new(0, 0, 0, 220)
n.BorderSizePixel = 0
n.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
n.FontSize = 6
n.TextStrokeTransparency = 0.9
n.TextSize = 18
n.TextColor3 = Color3.fromRGB(255, 255, 255)
n.Text = "Trail"
n.Font = 4
n.Parent = c
local p = Instance.new "TextButton"
p.Name = "D3"
p.AutoLocalize = false
p.Localize = false
p.ZIndex = 9
p.Size = UDim2.new(0, 84, 0, 20)
p.BorderColor3 = Color3.fromRGB(0, 0, 0)
p.BackgroundTransparency = 0.5
p.Position = UDim2.new(0, 83, 0, 190)
p.BorderSizePixel = 0
p.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
p.FontSize = 6
p.TextStrokeColor3 = Color3.fromRGB(255, 255, 255)
p.TextStrokeTransparency = 0.9
p.TextSize = 18
p.TextColor3 = Color3.fromRGB(255, 255, 255)
p.Text = "250 R$"
p.Font = 4
p.Parent = c
local q = Instance.new "TextButton"
q.Name = "D1"
q.AutoLocalize = false
q.Localize = false
q.ZIndex = 9
q.Size = UDim2.new(0, 75, 0, 20)
q.BorderColor3 = Color3.fromRGB(0, 0, 0)
q.BackgroundTransparency = 0.5
q.Position = UDim2.new(0.5, -78, 0, 140)
q.BorderSizePixel = 0
q.BackgroundColor3 = Color3.fromRGB(0, 255, 0)
q.FontSize = 6
q.TextStrokeTransparency = 0.75
q.TextSize = 18
q.TextColor3 = Color3.fromRGB(255, 255, 255)
q.Text = "10 R$"
q.Font = 4
q.Parent = c
local r = Instance.new "TextButton"
r.Name = "Shine"
r.AutoLocalize = false
r.Localize = false
r.ZIndex = 9
r.Visible = false
r.Size = UDim2.new(0, 82, 0, 20)
r.BorderColor3 = Color3.fromRGB(0, 0, 0)
r.BackgroundTransparency = 0.5
r.Position = UDim2.new(1, -82, 0, 220)
r.BorderSizePixel = 0
r.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
r.FontSize = 6
r.TextStrokeTransparency = 0.9
r.TextSize = 18
r.TextColor3 = Color3.fromRGB(255, 200, 0)
r.Text = "Shine"
r.Font = 4
r.Parent = c
local t = Instance.new "TextButton"
t.Name = "Hat"
t.AutoLocalize = false
t.Localize = false
t.ZIndex = 9
t.Visible = false
t.Size = UDim2.new(0, 84, 0, 20)
t.BorderColor3 = Color3.fromRGB(0, 0, 0)
t.BackgroundTransparency = 0.5
t.Position = UDim2.new(0, 83, 0, 220)
t.BorderSizePixel = 0
t.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
t.FontSize = 6
t.TextStrokeColor3 = Color3.fromRGB(255, 255, 255)
t.TextStrokeTransparency = 0.9
t.TextSize = 18
t.TextColor3 = Color3.fromRGB(255, 255, 255)
t.Text = "Crown"
t.Font = 4
t.Parent = c

local join = Instance.new("TextButton")
join.Name = "Join"
join.AutoLocalize = false
join.BackgroundColor3 = Color3.fromRGB(51, 95, 255)
join.BackgroundTransparency = 0.5
join.BorderColor3 = Color3.new()
join.BorderSizePixel = 0
join.Position = UDim2.fromOffset(0, 241)
join.Size = UDim2.new(1, 0, 0, 20)
join.Text = "Join our Community!"
join.TextColor3 = Color3.new(1, 1, 1)
join.TextSize = 18
join.TextStrokeTransparency = 0.9
join.Font = 4
join.ZIndex = 9
join.Parent = c

return a
