name: Bug Report 🐛
description: Report a problem you encountered with Kohl's Admin
labels: ["bug"]
body:
  - type: checkboxes
    id: existing
    attributes:
      label: Did you check for existing issues?
      description: You can do this by searching https://github.com/kohls-admin/kohls-admin/issues?q=is:issue+label:bug and making sure the bug is not related.
      options:
        - label: I have searched the open and **closed** bugs.
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you seeing the problem on?
      options:
        - PC
        - Mobile
        - Console
        - VR
      default: 0

  - type: input
    id: ver
    attributes:
      label: Version
      description: Include the version of Kohl's Admin shown in the dashboard title or by running `;version` command.
      placeholder: ex. 0.1.13

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Describe in detail what went wrong and what you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Repro
      description: Provide clear directions so someone else can see the issue on their machine too.

  - type: textarea
    id: logs
    attributes:
      label: Details
      description: |
        Attach anything that helps explain the problem.
        * **Logs:** Use the `;logs` command.
        * **Errors:** Press `F9` or type `/console` in chat.
        **Please ATTACH files, don't paste them directly.**
