name: Feature Request ✨
description: Suggest an improvement or new feature for Kohl's Admin
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Did you check for existing issues?
      description: You can do this by searching https://github.com/kohls-admin/kohls-admin/issues?q=is:issue+label:enhancement and making sure the request is not related.
      options:
        - label: I have searched the open and **closed** feature requests.
          required: true

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Explain what you'd like to see added or changed, why it's valuable, and what the current situation is like.
    validations:
      required: true
