return {
	chatCommands = { 115444443724463, 110019084552349 },

	donations = {
		{ name = "Tip", color = "#bf0", id = 5391355, assetId = 129760409821083 },
		{ name = "Gift", color = "#8f0", id = 5391356, assetId = 77680874300094 },
		{ name = "Donor", color = "#0f0", id = 933980650, assetId = 112699242861456 },
		{ name = "Tribute", color = "#0f8", id = 933582848, assetId = 88978146769822 },
		{ name = "Patron", color = "#0ff", id = 938480383, assetId = 115403290087767 },
		{ name = "Elite", color = "#80f", id = 939618404, assetId = 130880915606069 },
		{ name = "Epic", color = "#f0f", id = 936146448, assetId = 84349662672781 },
		{ name = "Hero", color = "#f08", id = 941076536, assetId = 129439770798699 },
		{ name = "Legend", color = "#f00", id = 941162509, assetId = 132161234381156 },
		{ name = "Mythic", color = "#000", id = 941006661, assetId = 89859349616824 },
		{ name = "Eternal", color = "#000", id = 983235767, assetId = 102980653148583 },
	},

	scriptedUGC = {
		{
			tip = "🕊️ <b>Light Wings</b>\n<font transparency='0.33'>Provides the following special effects in games using Kohl's Admin:</font>"
				.. "\n - Flying Animations 💫\n - Neon Material ✨\n\n<font transparency='0.66'>Animator: <b>@LuhHorsie</b>\nModeler: <b>@HyperbolicHydra</b>\nScripter: <b>@Scripth</b></font>",
			id = 133292294488871,
			equip = "rbxassetid://89119211625300",
			name = "Light Wings",
			level = 3,
		},
		{
			tip = "👑 <b>Light Crown</b>\n<font transparency='0.33'>Provides the following special effects in games using Kohl's Admin:</font>"
				.. "\n - Fire Effect 🔥\n - Neon Material ✨\n - Spinning 💫",
			id = 18966788838,
			equip = "rbxassetid://18966762965",
			name = "Light Crown",
			level = 2,
		},
		{
			tip = "🕊️ <b>Dark Wings</b>\n<font transparency='0.33'>Provides the following special effects in games using Kohl's Admin:</font>"
				.. "\n - Flying Animations 💫\n - Neon Material ✨\n\n<font transparency='0.66'>Animator: <b>@LuhHorsie</b>\nModeler: <b>@HyperbolicHydra</b>\nScripter: <b>@Scripth</b></font>",
			id = 110848154960799,
			equip = "rbxassetid://89119211625300",
			name = "Dark Wings",
			level = 3,
		},
		{
			tip = "👑 <b>Dark Crown</b>\n<font transparency='0.33'>Provides the following special effects in games using Kohl's Admin:</font>"
				.. "\n - Fire Effect 🔥\n - Neon Material ✨\n - Spinning 💫",
			id = 106645613603989,
			equip = "rbxassetid://18966762965",
			name = "Dark Crown",
			level = 2,
		},
		{
			tip = "🕊️ <b>Gold Wings</b>\n<font transparency='0.33'>Provides the following special effects in games using Kohl's Admin:</font>"
				.. "\n - Flying Animations 💫\n - Neon Material ✨\n\n<font transparency='0.66'>Animator: <b>@LuhHorsie</b>\nModeler: <b>@HyperbolicHydra</b>\nScripter: <b>@Scripth</b></font>",
			id = 92807314389236,
			equip = "rbxassetid://89119211625300",
			name = "Gold Wings",
			level = 3,
		},
		{
			tip = "👑 <b>Gold Crown</b>\n<font transparency='0.33'>Provides the following special effects in games using Kohl's Admin:</font>"
				.. "\n - Fire Effect 🔥\n - Neon Material ✨\n - Spinning 💫",
			id = 99317257118206,
			equip = "rbxassetid://18966762965",
			name = "Gold Crown",
			level = 2,
		},
	},
}
