name: Docs

on:
  push:
    branches:
      - master
    paths:
      - .moonwave/**
      - docs/**
      - model/**
      - src/**
      - moonwave.toml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm i -g moonwave@latest
      - name: Publish
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          moonwave build --publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
